name: Restore Turbo Cache

runs:
  using: "composite"
  steps:
    - name: Restore cached .turbo build
      uses: actions/cache/restore@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
