name: Save Turbo Cache

runs:
  using: "composite"
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
