name: Setup node_modules
description: Restores or reinstall the node_modules cache

runs:
  using: "composite"
  steps:
    - name: Trying to pull node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ github.repository }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies if cache is not found
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --ignore-scripts
