name: Compare Version

on:
  workflow_call:
    inputs:
      package_path:
        required: true
        type: string
    outputs:
      has_changed:
        description: Indicates whether the version has changed
        value: ${{ jobs.compare-version.outputs.has_changed }}

jobs:
  compare-version:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.version_check.outputs.has_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Pick packages
        run: |
          cp ${{ inputs.package_path }} current_package.json
          git reset --hard HEAD~1
          cp ${{ inputs.package_path }} previous_package.json

      - name: Compare package.json versions
        id: version_check
        run: |
          CURRENT_VERSION=$(jq -r '.version' current_package.json)
          PREVIOUS_VERSION=$(jq -r '.version' previous_package.json)
          HAS_CHANGED=false
          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            HAS_CHANGED=true
          fi
          echo "has_changed=$HAS_CHANGED" >> $GITHUB_OUTPUT
