name: Deploy @msw-devtools/connect

on:
  push:
    branches: ['master']

jobs:
  deploy-connect:
    name: Deploy @msw-devtools/connect
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commit
          fetch-depth: 0

      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-npm-deps

      - name: Publish
        uses: changesets/action@master
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}