name: Deploy @msw-devtools/demo

on:
  workflow_call:

jobs:
  compare-version:
    name: Guard
    uses: ./.github/workflows/compare-version.yml
    with:
      package_path: './packages/demo/package.json'

  deploy:
    name: Deploy @msw-devtools/demo
    needs: compare-version
    if: needs.compare-version.outputs.has_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-turbo-cache
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-npm-deps

      - name: Build package
        env:
          PUBLIC_PATH: /
        run: npm run build -- --filter=@msw-devtools/demo

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './packages/demo/dist/.'

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1