name: Deploy @msw-devtools/extension

on:
  workflow_dispatch:

jobs:
  deploy-extension:
    name: Deploy @msw-devtools/extension
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-npm-deps

      - name: Build @msw-devtools/extension
        run: npm run build -- --filter=@msw-devtools/extension

      - name: Archive @msw-devtools/extension
        run: zip -r dist.zip ./packages/extension/dist

      - name: Archive @msw-devtools/extension
        run: |
          tar -czf dist.tar.gz ./packages/extension/dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist.zip
            dist.tar.gz
          name: "@msw-devtools/extension"
          tag_name: "@msw-devtools/extension@latest"
