name: Deploy packages

on:
  push:
    branches: ['master']

jobs:
  changesets:
    name: Deploy packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commit
          fetch-depth: 0

      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-npm-deps

      - name: Publish
        uses: changesets/action@master
        id: changesets
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Debug hasChangesets Output
        run: |
          echo "Has Changesets: ${{ steps.changesets.outputs.hasChangesets }}"

      - name: Debug Outputs Object
        run: |
          echo "All Outputs: ${{ toJson(steps.changesets.outputs) }}"
